// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xdmhxyqkwfaunmbbqadv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhkbWh4eXFrd2ZhdW5tYmJxYWR2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg0NTYxNzcsImV4cCI6MjA3NDAzMjE3N30.ynPfW1-FviDSlei8mNGXzRZ8n45AErvU-xY-dP2n5tk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});